2024-11-09 19:35:25,013 - INFO - Start polling
2024-11-09 19:35:25,084 - INFO - Run polling for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:35:30,666 - INFO - Update id=887024512 is not handled. Duration 0 ms by bot id=7541101622
2024-11-09 19:35:30,666 - ERROR - Cause exception while process update id=887024512 by bot id=7541101622
TypeError: log_message() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: log_message() takes 1 positional argument but 3 were given
2024-11-09 19:36:37,289 - INFO - Polling stopped
2024-11-09 19:36:37,829 - INFO - Polling stopped for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:36:40,826 - INFO - Start polling
2024-11-09 19:36:40,885 - INFO - Run polling for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:36:43,885 - INFO - Update id=887024513 is not handled. Duration 16 ms by bot id=7541101622
2024-11-09 19:36:43,886 - ERROR - Cause exception while process update id=887024513 by bot id=7541101622
TypeError: log_message() missing 2 required positional arguments: 'event' and 'data'
Traceback (most recent call last):
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\logger.py", line 33, in log_message
    return await handler(event, data)  # Пропускаем выполнение обработчика дальше
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\command.py", line 191, in handler_command
    log_message(message)
TypeError: log_message() missing 2 required positional arguments: 'event' and 'data'
2024-11-09 19:37:38,808 - INFO - Polling stopped
2024-11-09 19:37:39,291 - INFO - Polling stopped for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:37:42,339 - INFO - Start polling
2024-11-09 19:37:42,403 - INFO - Run polling for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:38:09,772 - INFO - Update id=887024514 is not handled. Duration 0 ms by bot id=7541101622
2024-11-09 19:38:09,773 - ERROR - Cause exception while process update id=887024514 by bot id=7541101622
TypeError: log_message() missing 2 required positional arguments: 'event' and 'data'
Traceback (most recent call last):
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\logger.py", line 32, in log_message
    return await handler(event, data)  # Пропускаем выполнение обработчика дальше
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\command.py", line 191, in handler_command
    log_message(message)
TypeError: log_message() missing 2 required positional arguments: 'event' and 'data'
2024-11-09 19:39:49,690 - INFO - Polling stopped
2024-11-09 19:39:50,167 - INFO - Polling stopped for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:39:53,306 - INFO - Start polling
2024-11-09 19:39:53,379 - INFO - Run polling for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:39:56,232 - INFO - Update id=887024515 is not handled. Duration 0 ms by bot id=7541101622
2024-11-09 19:39:56,232 - ERROR - Cause exception while process update id=887024515 by bot id=7541101622
TypeError: log_message() missing 2 required positional arguments: 'event' and 'data'
Traceback (most recent call last):
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\logger.py", line 32, in log_message
    return await handler(event, data)  # Пропускаем выполнение обработчика дальше
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\command.py", line 224, in handler_command
    await first_cmd(message)
  File "C:\Users\Андрей\PycharmProjects\Telegram_bot_for_quantorium\command.py", line 74, in first_cmd
    log_message(message)
TypeError: log_message() missing 2 required positional arguments: 'event' and 'data'
2024-11-09 19:41:14,101 - INFO - Polling stopped
2024-11-09 19:41:14,594 - INFO - Polling stopped for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:41:17,636 - INFO - Start polling
2024-11-09 19:41:17,703 - INFO - Run polling for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:41:22,216 - INFO - Update id=887024516 is handled. Duration 328 ms by bot id=7541101622
2024-11-09 19:42:43,534 - INFO - Polling stopped
2024-11-09 19:42:44,117 - INFO - Polling stopped for bot @kvant363bot id=7541101622 - 'test'
2024-11-09 19:45:27,710 - INFO - РЎРѕР±С‹С‚РёРµ: <function CallableObject.call at 0x000001F0CE574FE0> | Р”Р°РЅРЅС‹Рµ: message_id=209 date=datetime.datetime(2024, 11, 9, 14, 45, 26, tzinfo=TzInfo(UTC)) chat=Chat(id=5867884661, type='private', title=None, username='main4562', first_name='б… б… б… б… б… ', last_name=None, is_forum=None, accent_color_id=None, active_usernames=None, available_reactions=None, background_custom_emoji_id=None, bio=None, birthdate=None, business_intro=None, business_location=None, business_opening_hours=None, can_set_sticker_set=None, custom_emoji_sticker_set_name=None, description=None, emoji_status_custom_emoji_id=None, emoji_status_expiration_date=None, has_aggressive_anti_spam_enabled=None, has_hidden_members=None, has_private_forwards=None, has_protected_content=None, has_restricted_voice_and_video_messages=None, has_visible_history=None, invite_link=None, join_by_request=None, join_to_send_messages=None, linked_chat_id=None, location=None, message_auto_delete_time=None, permissions=None, personal_chat=None, photo=None, pinned_message=None, profile_accent_color_id=None, profile_background_custom_emoji_id=None, slow_mode_delay=None, sticker_set_name=None, unrestrict_boost_count=None) message_thread_id=None from_user=User(id=5867884661, is_bot=False, first_name='б… б… б… б… б… ', last_name=None, username='main4562', language_code='ru', is_premium=None, added_to_attachment_menu=None, can_join_groups=None, can_read_all_group_messages=None, supports_inline_queries=None, can_connect_to_business=None, has_main_web_app=None) sender_chat=None sender_boost_count=None sender_business_bot=None business_connection_id=None forward_origin=None is_topic_message=None is_automatic_forward=None reply_to_message=None external_reply=None quote=None reply_to_story=None via_bot=None edit_date=None has_protected_content=None is_from_offline=None media_group_id=None author_signature=None text='РџР»Р°С‚РЅС‹Рµ РєСѓСЂСЃС‹' entities=None link_preview_options=None effect_id=None animation=None audio=None document=None paid_media=None photo=None sticker=None story=None video=None video_note=None voice=None caption=None caption_entities=None show_caption_above_media=None has_media_spoiler=None contact=None dice=None game=None poll=None venue=None location=None new_chat_members=None left_chat_member=None new_chat_title=None new_chat_photo=None delete_chat_photo=None group_chat_created=None supergroup_chat_created=None channel_chat_created=None message_auto_delete_timer_changed=None migrate_to_chat_id=None migrate_from_chat_id=None pinned_message=None invoice=None successful_payment=None refunded_payment=None users_shared=None chat_shared=None connected_website=None write_access_allowed=None passport_data=None proximity_alert_triggered=None boost_added=None chat_background_set=None forum_topic_created=None forum_topic_edited=None forum_topic_closed=None forum_topic_reopened=None general_forum_topic_hidden=None general_forum_topic_unhidden=None giveaway_created=None giveaway=None giveaway_winners=None giveaway_completed=None video_chat_scheduled=None video_chat_started=None video_chat_ended=None video_chat_participants_invited=None web_app_data=None reply_markup=None forward_date=None forward_from=None forward_from_chat=None forward_from_message_id=None forward_sender_name=None forward_signature=None user_shared=None
